# Generated by Django 6.1.1 on 2026-09-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Apontamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField()),
                ('devedor', models.CharField(max_length=50)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('especie', models.CharField(max_length=3)),
                ('n_titulo', models.CharField(max_length=11)),
                ('codigo_comarca', models.CharField(max_length=7)),
                ('codigo_cartorio', models.CharField(max_length=2)),
                ('nosso_numero', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=25)),
                ('valor_original', models.FloatField()),
                ('valor_enviado', models.FloatField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
