# Generated by Django 6.1.1 on 2026-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativosML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_apontamentos',
            name='comarca',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
